version: "2"
services:
    bonussite-app:
        build: .
        restart: always
        ports:
            - "3041:8080"
        links:
            - bonussite
        volumes:
            - ./uploads:/tmp/uploads        
    bonussite:
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
